data1=input("Data-1 :")
data2=input("Data-2 :")
data3=input("Data-3 :")
data4=input("Data-4 :")
data5=input("Data-5 :")

print("data1 =",data1,"data1 type ",type(str(data1)))
print("data2 ={} data typr {}".format(data2,type(data2)))
print(f'data3 = {data3} data type {type(data3)}')
print("data4 ={} data type {}".format(data4,type(data4)))
print("data 5= " + str(data5),"data type",str(type(data5)) )